#spring.application.name=vault
#spring.data.mongodb.uri=mongodb+srv://vaultuser:vault123@cluster0.jzqvpm7.mongodb.net/vaultDatabase?retryWrites=true&w=majority&appName=Cluster0
#spring.data.mongodb.auto-index-creation=true
#
#server.port=9095